name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Altere para 'master' se essa for sua branch principal

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Use a versão do Node.js que você prefere

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build
        env: # Define variáveis de ambiente para o passo de build
          VITE_APP_BASE_PATH: /${{ github.event.repository.name }}/ # Define a base path para o GitHub Pages

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages # A branch onde o GitHub Pages será publicado